_day_6_script: &day_6_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day1.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_6_script_md5: &day_6_script_md5
    1284dde1bab18233f470a679d5a234f2

_day_7_script: &day_7_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day2.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_7_script_md5: &day_7_script_md5
    5bd554df9c9bd5c40485a07956273cd9
    
_day_8_script: &day_8_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day3.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_8_script_md5: &day_8_script_md5
    505ef9e14e6ac3f80e691f4d0b5265a8
    
_day_9_script: &day_9_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day4.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_9_script_md5: &day_9_script_md5
    d82360a405c9ba1f1cc1d59b7707bc80
    
_day_10_script: &day_10_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day5.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_10_script_md5: &day_10_script_md5
    e53821b4b498bcecb4aa793e5dff67b5
    
_loop_script: &loop_script
    http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope_loop/raw/stimulus_loop.py?at=8ffefa1480845e26c379c8823f7faa202f7554ad

_loop_script_md5: &loop_script_md5
    2d5cf4c864e2e5f4c396918fbd13f6c7

### mtrain definitions
name: Openscope_Loop_v2

transitions:

  - trigger: progress
    source: DAY_6
    dest: DAY_7
    conditions: one_complete

  - trigger: progress
    source: DAY_7
    dest: DAY_8
    conditions: one_complete

  - trigger: progress
    source: DAY_8
    dest: DAY_9
    conditions: one_complete

  - trigger: progress
    source: DAY_9
    dest: DAY_10
    conditions: one_complete

  - trigger: manual
    source: DAY_10
    dest: GROUPA_60MIN_DAY1_2

  - trigger: manual
    source: GROUPA_60MIN_DAY1_2
    dest: GROUPA_90MIN_DAY3_4

  - trigger: manual
    source: GROUPA_90MIN_DAY3_4
    dest: GROUPA_120MIN_DAY5

  - trigger: manual
    source: GROUPA_120MIN_DAY5
    dest: PROD_GROUPA_LOOP

  - trigger: manual
    source: DAY_10
    dest: GROUPB_60MIN_DAY1_2

  - trigger: manual
    source: GROUPB_60MIN_DAY1_2
    dest: GROUPB_90MIN_DAY3_4

  - trigger: manual
    source: GROUPB_90MIN_DAY3_4
    dest: GROUPB_120MIN_DAY5

  - trigger: manual
    source: GROUPB_120MIN_DAY5
    dest: PROD_GROUPB_LOOP

  - trigger: manual
    source: PROD_GROUPB_LOOP
    dest: TEST_LOOP

stages:
    DAY_6:
        script: *day_6_script
        script_md5: *day_6_script_md5
        parameters:
            stage: DAY_6

    DAY_7:
        script: *day_7_script
        script_md5: *day_7_script_md5
        parameters:
            stage: DAY_7

    DAY_8:
        script: *day_8_script
        script_md5: *day_8_script_md5
        parameters:
            stage: DAY_8

    DAY_9:
        script: *day_9_script
        script_md5: *day_9_script_md5
        parameters:
            stage: DAY_9

    DAY_10:
        script: *day_10_script
        script_md5: *day_10_script_md5
        parameters:
            stage: DAY_10

    GROUPA_60MIN_DAY1_2:
        script: *loop_script
        script_md5: *loop_script_md5
        parameters:
            stage: GROUPA_60MIN_DAY1_2
            group: "movie_order_groupA"
            dev_mode: False
            data_folder: //allen/programs/mindscope/workgroups/openscope/2024-Loop/openscope_loop/data

    GROUPA_90MIN_DAY3_4:
        script: *loop_script
        script_md5: *loop_script_md5
        parameters:
            stage: GROUPA_90MIN_DAY3_4
            group: "movie_order_groupA"
            dev_mode: False
            data_folder: //allen/programs/mindscope/workgroups/openscope/2024-Loop/openscope_loop/data

    GROUPA_120MIN_DAY5:
        script: *loop_script
        script_md5: *loop_script_md5
        parameters:
            stage: GROUPA_120MIN_DAY5
            group: "movie_order_groupA"
            dev_mode: False
            data_folder: //allen/programs/mindscope/workgroups/openscope/2024-Loop/openscope_loop/data

    PROD_GROUPA_LOOP:
        script: *loop_script
        script_md5: *loop_script_md5
        parameters:
            stage: PROD_GROUPA_LOOP
            group: "movie_order_groupA"
            dev_mode: False
            data_folder: //allen/programs/mindscope/workgroups/openscope/2024-Loop/openscope_loop/data

    GROUPB_60MIN_DAY1_2:
        script: *loop_script
        script_md5: *loop_script_md5
        parameters:
            stage: GROUPB_60MIN_DAY1_2
            group: "movie_order_groupB"
            dev_mode: False
            data_folder: //allen/programs/mindscope/workgroups/openscope/2024-Loop/openscope_loop/data

    GROUPB_90MIN_DAY3_4:
        script: *loop_script
        script_md5: *loop_script_md5
        parameters:
            stage: GROUPB_90MIN_DAY3_4
            group: "movie_order_groupB"
            dev_mode: False
            data_folder: //allen/programs/mindscope/workgroups/openscope/2024-Loop/openscope_loop/data

    GROUPB_120MIN_DAY5:
        script: *loop_script
        script_md5: *loop_script_md5
        parameters:
            stage: GROUPB_120MIN_DAY5
            group: "movie_order_groupB"
            dev_mode: False
            data_folder: //allen/programs/mindscope/workgroups/openscope/2024-Loop/openscope_loop/data

    PROD_GROUPB_LOOP:
        script: *loop_script
        script_md5: *loop_script_md5
        parameters:
            stage: PROD_GROUPB_LOOP
            group: "movie_order_groupB"
            dev_mode: False
            data_folder: //allen/programs/mindscope/workgroups/openscope/2024-Loop/openscope_loop/data

    TEST_LOOP:
        script: *loop_script
        script_md5: *loop_script_md5
        parameters:
            stage: TEST_LOOP
            group: "movie_order_groupTEST"
            dev_mode: False
            data_folder: //allen/programs/mindscope/workgroups/openscope/2024-Loop/openscope_loop/data
